"""add_book_description

Revision ID: 005019b6ed22
Revises: 12edb603d2ec
Create Date: 2025-09-25 00:26:43.480499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005019b6ed22'
down_revision = '12edb603d2ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('books', 'isbn',
               existing_type=sa.VARCHAR(length=13),
               nullable=False)
    op.drop_index(op.f('ix_books_average_rating'), table_name='books')
    op.drop_index(op.f('ix_books_genres'), table_name='books', postgresql_using='gin')
    op.drop_index(op.f('ix_books_publication_date'), table_name='books')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_books_publication_date'), 'books', ['publication_date'], unique=False)
    op.create_index(op.f('ix_books_genres'), 'books', ['genres'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_books_average_rating'), 'books', ['average_rating'], unique=False)
    op.alter_column('books', 'isbn',
               existing_type=sa.VARCHAR(length=13),
               nullable=True)
    op.drop_column('books', 'description')
    # ### end Alembic commands ###
